# version: '3'
# services:
#   client:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./:/app

version: '3'
services:
  client:
    image: adityajnu14/client_arch32 #adityajnu14/client_x86_64
    ports:
      - "8080:8080"
    volumes:
      - ./:/app